version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: my_mongo_db
    ports:
      - "2718:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local # Khai báo driver cho volume